[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci --omit=dev --cache /tmp/.npm"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "NODE_ENV=production npm start"

[variables]
NODE_ENV = "production"
